# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Setup
title: Luke Anglin
tagline: Author and Engineer
description: Books
baseurl: ""
# url: http://localhost:4000/

author:
  name: Luke Anglin
  # url:            https://twitter.com/mdo

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "page:num"

# Custom vars
# Collections
version: 2.1.0

github: [metadata]

github-repo: https://github.com/luke-anglin/luke-anglin.github.io
defaults:
  - scope:
      path: "static/assets/media"
    values:
      image: true
